name: heimdall-test-postgres-mysql
services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: h-test
    ports:
      - "5432:5432"
  mysql:
    image: mariadb:12.3
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: h-test
    ports:
      - "3306:3306"