name: heimdall-test-postgres
services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: h-test
    ports:
      - "127.0.0.1:5432:5432"